version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.0
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./ssl:/etc/nginx/certs

  mariadb:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: super

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - mssql:/var/opt/mssql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: super
    volumes:
      - mysql:/var/lib/mysql

  postgres:
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  mariadb:
  mssql:
  mysql:
  postgres:
